<?php
/**
 * Implements hook_theme().
 */

function form_for_user_theme($existing, $type, $theme, $path) {
  $items = array();

  $items['form_for_user_content'] = array(
    'render element' => 'form',
    'template' => 'templates/form_for_user_content',
  );

  return $items;
}

/**
 * Implements hook_block_info().
 */

function form_for_user_block_info() {
  $blocks['form_for_user_block'] = array(
    'info' => t('Rend form'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */

function form_for_user_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'form_for_user_block':
      $block['subject'] = 'Please complete this registration form';

      $block['content'] = drupal_get_form('form_for_user_form');

      break;
  }

  return $block;
}

/**
 * Implements hook_form().
 */

function form_for_user_form($form, &$form_state) {
  $form = array();

  $form['userinfo'] = array(
    '#title' => t('User Information'),
    '#description' => t('You can add information about yourself here'),
    '#type' => 'fieldset',
   // '#tree' => TRUE,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#weight' => 0,
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'form_for_user') . '/css/styles.css',
      ),
      'js' => array(
        //drupal_get_path('module', 'form_for_user') . '/js/script-1.js',
        drupal_get_path('module', 'form_for_user') . '/js/script-2.js',
      ),
    ),
    '#theme' => 'form_for_user_content',

    '#attributes' => array(
      'class' => array(
        'form_for_user_content_wrapper'
      ),
    ),

  );

  $form['userinfo']['gender'] = array(
    '#type' => 'radios',
    '#title' => t('Gender:'),
    '#options' => array(
      0 => t('Man'),
      1 => t('Woman'),
    ),
    '#description' => t('Men or women?'),
    '#required' => TRUE,
    '#weight' => 1,
  );

  $form['userinfo']['form_for_user_first_name'] = array(
    '#title' => t('First name'),
    '#type' => 'textfield',
    '#description' => t('Enter your first name into this field'),
    '#default_value' => '',
    '#maxlength' => 255,
    '#size' => 25,
    '#attributes' => array(
      'placeholder' => t('Silvester'),
      'class' => array(
        'test-class',
        'test-class-1',
      ),
    ),
    '#required' => TRUE,
    '#element_validate' => array('form_for_user_form_first_name_validate'),
    '#weight' => 2,
  );

  $form['userinfo']['form_for_user_last_name'] = array(
    '#title' => t('Last name'),
    '#type' => 'textfield',
    '#description' => t('Enter your last name into this field'),
    '#default_value' => '',
    '#maxlength' => 255,
    '#size' => 25,
    '#attributes' => array(
      'placeholder' => t('Stallone'),
      'class' => array(
        'test-class-2',
        'test-class-3',
      ),
    ),
    '#required' => TRUE,
    '#element_validate' => array('form_for_user_form_last_name_validate'),
    '#weight' => 3,
  );

  /*$form['userinfo']['form_for_user_date'] = array(
    '#title' => t('Date. Year-month-day'),
    '#type' => 'textfield',
    '#description' => t('Enter a date into this field'),
    '#default_value' => '',
    '#maxlength' => 15,
    '#size' => 10,
    '#attributes' => array(
      'placeholder' => t('2015-02-15'),
    ),
    '#required' => TRUE,
    '#element_validate' => array('form_for_user_form_date_validate'),
    '#weight' => 4,
  );*/

  $form['userinfo']['comp_info'] = array(
    '#title' => t('Do you have a computer'),
    '#type' => 'radios',
    '#options' => array(
      'no' => t('No'),
      'yes' => t('Yes')
    ),
    '#required' =>TRUE,
    '#weight' => 5,
  );

  $form['userinfo']['comp_info']['status'] = array(
    '#title' => 'Select a operation system',
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#states' => array(
      'visible' => array(
        ':input[name="comp_info"]' =>array('value' => 'yes'),
      ),
    ),
    '#weight' => 6,
  );

  $form['userinfo']['comp_info']['status']['operation_system'] = array(
    '#type' => 'select',
    '#title' => t('Pre installed operating system'),
    '#default_value' => 'Windows',
    '#description' => t('Select your operation system in this field'),
    '#required' => TRUE,
    '#options' => array(
      'Windows' => t('Windows'),
      'Linux' => t('Linux'),
      'FreeBSD' => t('FreeBSD'),
      'Dos' => t('MSDos'),
    ),
    '#weight' => 7,
  );

  $form['userinfo']['family_status'] = array(
    '#title' => t('Select your family status'),
    '#type' => 'select',
    '#description' => t('Please, select you family status in this field'),
    '#default_value' => 'Married',
    '#required' => TRUE,
    '#options' => array(
      'Married' => t('Married'),
      'Not_married' => t('Not_married'),
      ),
    '#weight' => 8,
  );

  $form['actions'] = array(
    '#type' => 'actions',
  );

  $form['actions']['form_for_user_form_submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send'),
    '#submit' => array(
      'form_for_user_form_submit',
    ),
  );

  $form['actions']['form_for_user_form_submit_some_element'] = array(
    '#type' => 'submit',
    '#value' => t('Second submit'),
    '#submit' => array(
      'form_for_user_form_submit_custom',
    ),
  );

  $form['actions']['form_for_user_form_submit_all_form'] = array(
    '#type' => 'submit',
    '#value' => t('Third submit'),
    '#submit' => array(
      'form_for_user_form_submit_custom_2',
    ),
  );

  //$form['#submit'][] = 'form_for_user_form_submit';

  //$form['#submit'][] = 'form_for_user_form_submit_custom';

  $form['actions']['form_for_user_form_submit_cancel'] = array(
    '#type' => 'button',
    '#value' => t('Cancel'),
    '#limit_validation_errors' => array(),
  );

  return $form;
}

function  form_for_user_form_validate($form, &$form_state) {
  $values = $form_state['values'];

  if (!preg_match('/^[a-z\s]+$/i', $values['form_for_user_first_name'])) {
    form_set_error(
      'form_for_user_first_name',
      t('The first name contains invalid characters')
    );
  }
}

function form_for_user_form_date_validate($form, &$form_state){

  $values = $form_state['values'];

  if(empty($values['form_for_user_date'])){
    form_set_error(
      'form_for_user_date',
      t('The field for date is empty. Please, enter a date correct.')
    );
  }
  elseif (!preg_match("/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/", $values['form_for_user_date'])) {
    form_set_error(
      'form_for_user_date',
      t('The date field contains invalid characters.')
    );
  }

}

function  form_for_user_form_first_name_validate($form, &$form_state) {
  $values = $form_state['values'];

  if (!preg_match('/^[a-z\s]+$/i', $values['form_for_user_first_name'])) {
    form_set_error(
      'form_for_user_first_name',
      t('The first name contains invalid characters')
    );
  }
}

function  form_for_user_form_last_name_validate($form, &$form_state) {
  $values = $form_state['values'];

  if (!preg_match('/^[a-z\s]+$/i', $values['form_for_user_last_name'])) {
    form_set_error(
      'form_for_user_last_name',
      t('The last name contains invalid characters')
    );
  }
}

function form_for_user_form_submit($form, &$form_state){

  $values = $form_state['values'];

  $gender = $values['gender'] ? "Woman" : "Man";

  if ($gender == "Woman")
  {
    $gender_1 = "She";
  }
  else
  {
    $gender_1 = "He";
  }

  if ($values['comp_info'] == "no")
  {
    $yes_no_comp = "does not have a computer";
  }
  else
  {
    $yes_no_comp = "has a computer";
  }

  $message = t('@name is a @gender. @gender_1 @yes_no_comp.', array(
      '@name' => $values['form_for_user_first_name'] .' '. $values['form_for_user_last_name'],
      '@gender' => $gender,
      '@gender_1' =>$gender_1,
      '@yes_no_comp' =>$yes_no_comp,
    )
  );

  $c = $values['gender'];

  variable_set('gender', $c);

  $c = $values['form_for_user_first_name'];

  variable_set('form_for_user_first_name', $c);

  $c = $values['form_for_user_last_name'];

  variable_set('form_for_user_last_name', $c);

  drupal_set_message($message);

}

function form_for_user_form_submit_custom($form, &$form_state) {

  $values = $form_state['values'];

  $married_yes_no = $values['family_status'];

  $message = t(' @name is @married_yes_no.', array(
      '@name' => $values['form_for_user_first_name'] .' '. $values['form_for_user_last_name'],
      '@married_yes_no' => $married_yes_no,
    )
  );

  drupal_set_message($message);
}

function form_for_user_form_submit_custom_2($form, &$form_state) {
  drupal_set_message(t('Custom submit has been triggered'));
}

/**
 * Implements hook_form_FORM_ID_alter().
 */

function form_for_user_form_form_for_user_form_alter(&$form, &$form_state, $form_id) {
// add a date_field to form using hook_form_form_id_alter function
 if ($form_id == 'form_for_user_form'){

   $form['userinfo']['form_for_user_date'] = array(
     '#title' => t('Date. Year-month-day'),
     '#type' => 'textfield',
     '#description' => t('Enter a date into this field'),
     '#default_value' => '',
     '#maxlength' => 15,
     '#size' => 10,
     '#attributes' => array(
       'placeholder' => t('2015-02-15'),
     ),
     '#required' => TRUE,
     '#element_validate' => array('form_for_user_form_date_validate'),
     '#weight' => 4,
   );

 }

 //realize a fifth section of the homework

 $form['actions']['form_for_user_form_submit_all_form']['#submit'] = $form['actions']['form_for_user_form_submit']['#submit'];

}
